### ISSUE TITLE
Save button does nothing in version 1.0 and 1.1

### ISSUE THREAD

**Issue by ran-sama** [teddy-gustiaux/default-bookmark-folder#1]
Salut,

very nice addon, just what I needed, but when I customize the default folder and enable the override the save button does nothing. If I leave options or restart Firefox everything is still unconfigured.

Firefox 58 is used. I will provide more information, just not sure what else I could tell to help.

Idea: It might be related to privacy settings. How do you store the config?

Edit:
You should use the browser-extension-data directory in the userprofile. I see no folder there with your extension name. Every popular addon relies on this to store settings. I hope you can help, please understand I am very happy about this addon. I just cannot use it yet.

e.g.
/browser-extension-data/default-bookmark-folder@gustiaux.com.xpi/storage.js

E̶d̶i̶t̶ ̶2̶:̶
̶S̶t̶r̶a̶n̶g̶e̶ ̶b̶e̶h̶a̶v̶i̶o̶u̶r̶,̶ ̶I̶ ̶s̶p̶a̶m̶m̶e̶d̶ ̶t̶h̶e̶ ̶S̶a̶v̶e̶ ̶b̶u̶t̶t̶o̶n̶ ̶a̶b̶o̶u̶t̶ ̶2̶0̶ ̶t̶i̶m̶e̶s̶ ̶i̶n̶ ̶r̶a̶p̶i̶d̶ ̶s̶u̶c̶c̶e̶s̶s̶i̶o̶n̶.̶ ̶T̶h̶i̶s̶ ̶t̶i̶m̶e̶ ̶t̶h̶e̶ ̶s̶e̶t̶t̶i̶n̶g̶s̶ ̶c̶a̶r̶r̶i̶e̶d̶ ̶o̶v̶e̶r̶ ̶a̶f̶t̶e̶r̶ ̶r̶e̶s̶t̶a̶r̶t̶.̶ ̶I̶ ̶w̶i̶l̶l̶ ̶t̶r̶y̶ ̶t̶o̶ ̶r̶e̶p̶l̶i̶c̶a̶t̶e̶ ̶i̶t̶ ̶o̶n̶ ̶a̶ ̶n̶e̶w̶ ̶p̶r̶o̶f̶i̶l̶e̶.̶ ̶B̶u̶t̶ ̶i̶t̶ ̶s̶e̶e̶m̶s̶ ̶o̶k̶a̶y̶ ̶n̶o̶w̶.̶

Edit 3:
Retry on a clean profile. All default settings. Definitely broken on different locales than en_US / fr or which you are using. H̶o̶w̶ ̶I̶ ̶g̶o̶t̶ ̶i̶t̶ ̶t̶o̶ ̶s̶a̶v̶e̶ ̶o̶n̶ ̶m̶y̶ ̶o̶t̶h̶e̶r̶ ̶p̶r̶o̶f̶i̶l̶e̶?̶ ̶I̶ ̶d̶o̶n̶'̶t̶ ̶k̶n̶o̶w̶.̶ ̶M̶u̶s̶t̶ ̶h̶a̶v̶e̶ ̶m̶a̶s̶h̶e̶d̶ ̶b̶e̶ ̶t̶h̶e̶ ̶b̶u̶t̶t̶o̶n̶ ̶a̶ ̶1̶0̶0̶ ̶t̶i̶m̶e̶s̶.̶

See for yourself please: https://www.youtube.com/watch?v=jLcFbdgHxUI

Edit 4: broken on my main profile again as well

**Comment by teddy-gustiaux** [comment]
Hello,

Thank you for providing all those details and the video! It is very helpful and I am glad to hear that this add-on can be useful to someone else.

You are indeed experimenting a strange behavior indeed. I have not encountered such problem myself, however, I am going to investigate and try a different way to store the configuration.

**Comment by teddy-gustiaux** [comment]
After investigation, it appeared that I was using `storage.sync` instead of `storage.local `. The fact that I was using Firefox Sync hid the issue to me. I committed the changes, and I am going to publish version 1.2 (which also fixes other issues). Please let me know if you are still having the same problem with the new version!

**Comment by ran-sama** [comment]
Thank you for providing a new version. Even though the drop down menu jumps back to select again, saving whilst the first slider is on works now. I can see the storage.js being populated with information about the folders I select. This is expected behaviour. I guess it will work now, not a single problem so far 👍

**Comment by teddy-gustiaux** [comment]
Glad to hear it is working properly! I have published a minor update (1.2.2) that should fix the drop-down menu display issue. Please do not hesitate to open a new issue on GitHub if the problem is still here after the update to the latest version. 👍
