### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by Rictusempra** [teddy-gustiaux/default-bookmark-folder#10]

**Comment by teddy-gustiaux** [comment]
Good idea! I will look into this for a future release! 😃

**Comment by teddy-gustiaux** [comment]
The newly released version `2.3.0` now supports internationalization! 😃

I have also added the French translation, but if anyone wants to submit a PR to add other languages, please feel free to do so! I will add information regarding this in the README and other places very soon.
