### ISSUE TITLE
Add a Drop-down Menu

### ISSUE THREAD

**Issue by Riajyuu** [teddy-gustiaux/default-bookmark-folder#11]
This is designed to search for folders where a bookmark is about to be added. Perhaps middle click?

**Comment by teddy-gustiaux** [comment]
This feature will be part of the next version. 🙂 

As it is [not possible ](https://bugzilla.mozilla.org/show_bug.cgi?id=1405031) to set a different action depending on the type of click, a browser action (toolbar icon) will be used. It will allow users to search for a folder and quickly bookmark the current page into it.

**Comment by teddy-gustiaux** [comment]
This is part of [version `2.7.0`](https://github.com/teddy-gustiaux/default-bookmark-folder/releases/tag/v2.7.0).
