### ISSUE TITLE
Quick bookmarking to folder is erroneous

### ISSUE THREAD

**Issue by q3cap** [teddy-gustiaux/default-bookmark-folder#111]
# This is a Bug Report

## Description

On a Mac, using Firefox Quantum (69.0.3 (64-bit)):

Trying desperately to use "Bookmark to folder" via shortcut `Shift + Opt + M`. It opens a menu with a search field saying "Search folders...". Headline: "Quick bookmarking to folder". I enter a folder name, select it with my mouse. Menu disappears. Bookmark is set. But then, when I look into the folder I selected, I don't see the bookmark. Searching the bookmark, I see it in a totally different folder. - What am I missing?!

## Steps to reproduce the problem

1. Trying to set a bookmark to folder via shortcut `Shift + Opt + M`.
2.  It opens a menu with a search field saying "Search folders...". Headline: "Quick bookmarking to folder". 
3.  I enter a folder name, select it with my mouse. Menu disappears. Bookmark is set. 
4. Bookmark has landed in a totally different folder. 

## Expected behavior
Bookmark should be in the entered / selected folder.

## Specifications

- Version of the add-on: 2.10.1

- Firefox edition: Quantum
- Firefox version: 69.0.3 (64-bit)
- Firefox language: English 

- Platform/OS: Windows / macOS / Linux / Other (please specify)
- Platform/OS version: MacOS Catalina

**Comment by davebrny** [comment]
im having the same problem (firefox 70 on linux/pop_os)
a lot of the time the bookmark ends up in the "other bookmarks" folder. i think a few times its gone into the correct folder but i havnt been checking it that much to know for sure

**Comment by teddy-gustiaux** [comment]
Thank you @q3cap and @davebrny for reporting this issue!
After investigation, I found it was due to the way the `onClick` event was handled. A fix is ready and will be out with the next version, which I hope to be soon! 🙂
