### ISSUE TITLE
Icon changes position in address

### ISSUE THREAD

**Issue by nollinvoyd** [teddy-gustiaux/default-bookmark-folder#119]
# This is a Bug Report

## Description
I position the "Quickly Bookmark this page" Icon in a specific spot in the address bar, but it changes position by itself.

## Steps to reproduce the problem
1. I want it just to the left of the "Bookmark this page" star, which is situated at the far right side of the address bar.  
2. I right click "Quickly Bookmark this page", select "Remove from address bar", 
3.  I click the page actions button, right click the "Quickly Bookmark this page", and select "Add to address bar", whereupon it appears next to the "Bookmark this page" star
4.  After I restarted the browser, the position of the "Quickly Bookmark this page" moved two sopys to the left

## Expected behavior
It should maintain it's position

- Version of the add-on: 2.10.1

- Firefox edition: Firefox (regular edition) 
- Firefox version: 70.01
- Firefox language: English

- Platform/OS: Windows
- Platform/OS version: 10

**Comment by sleek22** [comment]
I have the following code in my userChrome.css to position various icons in my address bar. In my case, I want the default-bookmark-folder always furthest to the right, with the star button just to the left of that, and other stuff to the left of that.

> #pageAction-urlbar-default-bookmark-folder_gustiaux_com {-moz-box-ordinal-group: 99 !important;} /* Default Bookmark Folder */

> #star-button-box {-moz-box-ordinal-group: 98 !important;} /* this is wrapper for star-button, star-button alone does not work */

> #pageAction-urlbar-_e39749e2-f9b8-4dcb-ac41-c729c0320888_ {-moz-box-ordinal-group: 97 !important;} /* Browse Later */

If you have other icons, you can use Browser Toolbox in Web Developer to find their ID codes, and then situate them where you want in the address bar.

**Note: This works for the last few versions of Firefox,. I'm currently on Firefox 70. In earlier versions, the ID codes were different. For those using a much earlier version of Firefox, use Browser Toolbox to find the correct ID codes.**

**Comment by nollinvoyd** [comment]
@sleek22 
> 
> In my case, I want the default-bookmark-folder always furthest to the right, with the star button just to the left of that,
> 
You must be a mind reader.  That's something I wanted all along.  Works great.  Thanks!

**Comment by teddy-gustiaux** [comment]
Firefox does not allow users to re-order the add-on icons in the address bar (at the time I am writing this), and there is no API I could find that would allow this either. Therefore, it is not something the add-on can manage on its own.

For those willing to spend the time and efforts, I would direct them to the solution indicated by @sleek22 above using the `userChrome.css` file.
