### ISSUE TITLE
Click default bookmark icon to un-bookmark

### ISSUE THREAD

**Issue by ShaunDreclin** [teddy-gustiaux/default-bookmark-folder#12]
I like the default bookmark button and menu, the only thing I don't like is that you can't click the star again to easily un-bookmark something if you accidentally clicked it. Is is possible for you to add that feature to the default firefox bookmark star?

**Comment by teddy-gustiaux** [comment]
Hello (and sorry for the late response)! As of today, it is not possible to override the behavior of the default bookmark button of Firefox. This is one of the reasons I created this add-on.

If you want to quickly un-bookmark a page, I recommend you to enable the quick bookmark icon in the settings of Default Folder Bookmark. It will add an icon in the address bar, that allows to (un-)bookmark a page with only one click. This feature has its own set of options, so feel free to play around.

Hope it helps! 😃

**Comment by ShaunDreclin** [comment]
Ahh right I had forgotten the addon api lost a ton of features recently. Oh well!

**Comment by teddy-gustiaux** [comment]
Yes, the arrival of WebExtensions has changed quite a lot. Mozilla is adding back more features with each new release of Firefox, but it will take a while before we have the same capabilities as we used to (if that happens at all).
