### ISSUE TITLE
Avast reports this addon as malware-ish

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [teddy-gustiaux/default-bookmark-folder#14]
Yeah, I know, this is complete and utter BS, but I imagine the addon manager could drop Avast an email about it. I've occasionally contacted them for false positives of one sort or another, they do take reports into consideration, after 2-5 days usually.

I've had this morning a popup message from Avast, telling me the Default Bookmark Folder had a bad reputation (2/5 stars, whatever it may come from) because it had the capacity to monitor my internet usage, and Avast recommended deactivated it.

So, here's for the report. Sorry to bother with that.

**Comment by teddy-gustiaux** [comment]
Hello! Thank you for taking the time to report this, and sorry for the late response.

I installed Avast and the add-on, and then run a simple scan. The message is indeed present, although I do not understand why. I have reported the issue to Avast. I am hoping they will fix it!

**Comment by teddy-gustiaux** [comment]
I got a response from Avast today:

> Hello,
> 
> Thank you for reporting this.
> 
> I checked this problem with our developers and the rating of the ​"Default Folder Bookmark" extension was changed to 4 stars. Please allow up to 24 hours for this change to take effect.
> 
> We are sorry for the inconvenience.  If you have any further questions, don't hesitate to contact me again.
> 
> Best Regards,
> Prokop
> The Avast Support Team

I run a new scan, and no reports about the add-on. I am going to try again on a different machine to make sure, but it looks like the issue has been resolved.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
I am glad for you Teddy, well done :)

That said, if you'll pardon my rant, this is plain ridiculous on Avast part. These ratings are supposed to be community-generated, however a developer casting a look pumps the rating to four stars. Not three, not five, four.
It couldn't look *more* bogus and, as it's arbitrary, worthless. 
Really, silly that had the extension blocked before.
Anyway, good it's over, your extension is a blessing for FF users, thank you one last time :)
