### ISSUE TITLE
Request: specific explanation of quick bookmark icon

### ISSUE THREAD

**Issue by onebod** [teddy-gustiaux/default-bookmark-folder#17]
Hi!
I may be missing something obvious to others, but thought I'd ask.
This is an excellent add-on - I gave 5 stars.

I can't understand what the quick bookmark icon is for though.
If the only difference is that it removes a bookmark with a single click, I'll just keep using the default one so I don't accidentally delete a bookmark.

Or is there a difference between pressing Ctrl+D vs hitting the default "bookmark this page" (blue) star in the address bar?
Is it because your add-on can replace some functionality but not that of the default star?

Maybe I'm not understanding some feature of the Other Bookmarks forlder.
Does the Other Bookmarks folder act like a smart folder?
Sometimes it wouldn't allow me to delete bookmarks within it.
It even repopulated itself with bookmarks from several years ago sometimes.
Possible synching with my Android phone...?

Regards,
James

**Comment by teddy-gustiaux** [comment]
Hello!

First, thank you for your review! Regarding your question, you have come to the right place. All questions are welcome here! 😃

The quick bookmark icon role is indeed to be able to bookmark a page in a single click or to remove that bookmark, again with a single click. The icon is an optional feature, and it might not be useful for you. I personally use it quite often when I bookmark pages during my web searches, as it saves me one click for every bookmark. However, it is true that it makes it easy to remove a bookmark by mistake, so I have opened a dedicated issue for this problem (#21).

The quick bookmark icon settings are completely independent from the settings of the built-in bookmarking system of Firefox (aka, the default blue star). In both cases, you are able to choose the default bookmark folder you prefer (and they can be different).

Using the Firefox built-in Ctrl+D shortcut is the same as clicking on the default blue star.

Regarding the Other Bookmarks folder, from my understanding it is a just a regular folder. You might have been experiencing syncing issues, which happens sometimes.

Hope it helps! Let me know if you have more questions!

**Comment by teddy-gustiaux** [comment]
Considering the question answered and closing the issue. Please feel free to reopen it if you deem it necessary. 😃
