### ISSUE TITLE
Does not seem to work when default location is set to bookmarks toolbar

### ISSUE THREAD

**Issue by CottonEaster** [teddy-gustiaux/default-bookmark-folder#2]
I installed the extension, set the default location to the bookmark bar, book marked a page through what I presume was the correct icon - the one that says 'bookmark it', yes? - and the bookmark did not appear on the bookmark bar.

**Comment by teddy-gustiaux** [comment]
Hello!

You seem to have used to correct icon, yes. In the add-on settings page, did you enable the option "Override default location"? If this option is disabled, Firefox will continue to use the built-in default bookmark location (which is "Other Bookmarks").

You need to enable this option and save the settings to use the new location you have selected (see screenshot). Please let me know if it helps! :smiley:

![override_option](https://user-images.githubusercontent.com/26365722/32959886-061c649c-cb91-11e7-84ab-150afd780468.png)

**Comment by CottonEaster** [comment]
Thanks - but I think I had the 'override' option enabled. I say 'I think' because I tried the extension on Windows and I am now on my Linux computer. On the Linux computer, I cannot find a way of making the extension _do anything at all_, though I have found, and configured, the options page. Part of the problem, I think, is your documentation: the text underneath 'Enable "quick bookmark icon"' does not seem to say anything about what that icon is, let alone give a picture of it.

**Comment by teddy-gustiaux** [comment]
OK, thank you for the feedback!

Regarding the "quick bookmark icon", the "how to use" section gives more information about it, but I will try to add a description and an example of the icon to the options page in a future release to make it easier. The icon is a round star icon in the address bar. If the current page is bookmarked, the icon color will change to red. Here are two screenshots: when the current page is not bookmarked and when it is.

![icon-page_not_bookmarked](https://user-images.githubusercontent.com/26365722/32984594-afe39392-cc77-11e7-88a1-22a1d29f1c27.png)
![icon-page_bookmarked](https://user-images.githubusercontent.com/26365722/32984593-afce4dac-cc77-11e7-8e4e-48e9a38eaade.png)

Regarding your other issues, could you provide me with more information regarding your installation so I can try to replicate the behavior you are experimenting? Mainly your Firefox version and your Linux distribution and its version, as well as your configuration of the add-on (a screenshot would do the trick). You can provide me with the same information regarding your Windows installation if you did enable the "override" option (when you get the chance to check of course).

Thank you!

**Comment by CottonEaster** [comment]
**Instructions**

&nbsp;&nbsp;&nbsp;&nbsp;Thank you for explaining things to me and for undertaking to clarify the instructions that you provide for all users. Here are some suggestions for improving the text on your extension's addOn Page within Firefox.

- The text, `Only show page as bookmarked if said bookmark is in the default folder` would be better as, `Only show page as bookmarked if the bookmark is in the *default* folder` (if indeed that is what you mean).

- `Override default location` would better as, `Enable override of Firefox's default bookmark location.`


**Bookmarks not being added**

&nbsp;&nbsp;&nbsp;&nbsp;The extension continues not to work for me, on either Windows (8.1) or Linux (Mint Cinnamon). I use Firefox 57.0 on both. The problem is that _I have set bookmarks to appear on the bookmarks toolbar and they do not_. I have not yet tested with other default locations. Here is an image of my options as configured on the Windows machine:

![image](https://user-images.githubusercontent.com/9998846/33133314-42d4a3de-cf94-11e7-8a4a-34cb1f0b3491.png)

**Comment by teddy-gustiaux** [comment]
Hello again (and sorry for the delay)!

I have been testing the extension on different Linux distributions (Mint, Ubuntu and Debian) with different desktop environments (Cinnamon, Gnome, XFCE) with the settings you provided, and I have unfortunately not be able to reproduce the behavior you are experiencing. Hence, it is complicated for me to work on resolving this issue.

I have just released a new major version `2.0.0`. One of the main changes is the fact that the add-on settings now have a dedicated page, with more explanations and flexibility.

That being said, could you please tell me if you are still experiencing the same issue with this new version? Here are a few more things that could be helpful for me to know if you are still having problems:
- Is the problem happening only with the quick bookmarking or with the built-in bookmarking, or both?
- Is the problem still happening when you select a location other than the Bookmarks Toolbar?
- Is the bookmark being added at all? In the folder you selected, or maybe in Firefox's default location (Other Bookmarks) or elsewhere?

Thank you for your help!

**Comment by CottonEaster** [comment]
Dear Teddy

    I think that the problem was with my bookmarks folders - on, though, three computers (one Windows, two Linux), which suggests something has gone wrong with Firefox itself. Anyhow, after all sorts of craziness - bookmarks (created via the native functionality) visible viewed in one way, but not in another; restoring of stored bookmarks putting them into the wrong folders - everything now seems to work, though, oddly, I've been offered the new version of your extension on one Linux computer but not the other, and not on Windows.

    The new version of the extension is an improvement, clarity-wise, though I feel there is still a way to go.

    Finally: your extension seems not to save webpages as a single page, which is a shame.

    The new version of your extension has yet to arrive on Windows, though I received it on Linux.

**Comment by teddy-gustiaux** [comment]
I am glad to hear things are working properly now, and sorry about the issues you experienced with Firefox. I am not sure I understand what you mean about saving web pages though, as the add-on only allows (on purpose) to bookmark pages.

If you are having other issues with the add-on, I recommend you to open another issue on GitHub. I will be happy to help! As the problem raised up in this issue seems fixed, I am going to close it.

Do not hesitate to to submit a pull request if you have ideas for improving the options page wording. 😃
