### ISSUE TITLE
Why bothering me with "The quick bookmark icon is disabled"?

### ISSUE THREAD

**Issue by CodingMarkus** [teddy-gustiaux/default-bookmark-folder#201]
When I disable the quick bookmark feature, as all I need this addon for is choosing a default folder for Firefox bookmarks, why do I get this \
![2](https://user-images.githubusercontent.com/26418089/78502053-503d1400-775f-11ea-9990-38d742c4c4df.png) when I click that in the address bar \
![1](https://user-images.githubusercontent.com/26418089/78502062-5d5a0300-775f-11ea-95aa-63fff465ab40.png) \
?

Why don't you just remove the entry from the menu?

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions

**Comment by teddy-gustiaux** [comment]
I am not remembering exactly when this got resolved, but on the latest version of the add-on at the time of writing, the quick bookmarking icon is no longer visible if the feature is not enabled.
