### ISSUE TITLE
Fails for bookmarks created inside the reader mode

### ISSUE THREAD

**Issue by mkirisame** [teddy-gustiaux/default-bookmark-folder#22]
You may be aware of the nice reader mode when you click the sheet icon on some news websites.

The icon is part of firefox itself, it is located in the address bar.
Edit: or if F9 is hit

Here is an example how a bookmark using this mode looks like:
about:reader?url=https%3A%2F%2Ftext.npr.org%2Fs.php%3FsId%3D615835080

It will ignore your addon and go in the "other bookmarks" folder if you open the URI and try to save it with CTRL+D.

**Comment by teddy-gustiaux** [comment]
Thank you for reporting this issue! I am working on a fix to support the Reader Mode in the add-on. 😃

**Comment by mkirisame** [comment]
Working good here now, thanks a lot!
