### ISSUE TITLE
 Feature Request: Save Bookmarksfolder to different locations

### ISSUE THREAD

**Issue by novski** [teddy-gustiaux/default-bookmark-folder#23]
To sync bookmarks over any cloud like dropbox or nextcloud it wold be nice to be able to adress a bookmark folder to a different location so a shareing with work coleagues and private bookmarks can be established easily...

**Comment by teddy-gustiaux** [comment]
Hello (and sorry for the late response)!

**Comment by teddy-gustiaux** [comment]
Hello (and sorry for the late response)!

This would be a nice feature to have indeed! Unfortunately, I am not able to take care of this, as Firefox simply does not offer (for the moment at least) any APIs allowing to do what you described. It is not possible to save bookmarks elsewhere than the internal system of Firefox, and for security reasons, add-ons cannot access the file system.

Sorry again for the delay, and I hope you are finding this add-on useful! 😃
