### ISSUE TITLE
Quick Bookmarking To Folder - activate using enter/return

### ISSUE THREAD

**Issue by psietos** [teddy-gustiaux/default-bookmark-folder#250]
# This is an Improvement Request

**Which component or feature of the add-on is your improvement request related to? Please describe.**
quick bookmarking to folder.

**Describe the improvement you would like**
allow use of keyboard's enter/return to register the selected folder to be bookmarked  with "quick bookmarking to folder".  

**Describe alternatives you have considered**
use of mouse click.    

**Additional context**
while I am able to trigger and navigate the add-on with use of keyword only, I am unable to enter the selected folder using the keyboards enter/retunr key.  
![Screen Shot 2020-06-13 at 11 54 17](https://user-images.githubusercontent.com/66878499/84573155-c1ef9a80-ad6c-11ea-8978-ba7143551bf6.png)

**Comment by teddy-gustiaux** [comment]
This improvement is available as part of the next minor version (2.13.0) of the add-on. The new release has been submitted for review- please note it may take a few days for the update to be available to end-users. 🙂
