### ISSUE TITLE
Please stop, or at least make optional, the opening of a page every time the extension is updated

### ISSUE THREAD

**Issue by CottonEaster** [teddy-gustiaux/default-bookmark-folder#27]
Other extensions offer such functionality, i.e. don't pester the user when s/he would rather they do not.

Thanks.

**Comment by teddy-gustiaux** [comment]
Sounds like a good idea! I will add an option to open the changelog page if the add-on is updated, but I will leave it disabled by default.

**Comment by teddy-gustiaux** [comment]
The option is available in the new version `2.4.0` released today.

**Comment by CottonEaster** [comment]
Good! Thank you! However, _where_ is that option?
