### ISSUE TITLE
Navigate Quick Bookmarking To Folder results with up and down arrow keys

### ISSUE THREAD

**Issue by FichteFoll** [teddy-gustiaux/default-bookmark-folder#270]
Pretty much as the title says. For proper keyboard usage of this feature, there needs to be a way to select a search result that you can press <kbd>Enter</kbd> (#250) on. Currently, this can be done with the <kbd>Tab</kbd> key, but that's crude because you have to press it twice to go to the first result *and* it removes focus from the input, so you can't continue typing to refine your query.

**Comment by teddy-gustiaux** [comment]
These improvements are available as part of the next minor version (2.13.0) of the add-on. The new release has been submitted for review- please note it may take a few days for the update to be available to end-users. 🙂

**Comment by FichteFoll** [comment]
I was finally able to test this out and I have to say the UX is much better now. However, sometimes starting to type or hitting the return key too early seems to be swallowed and I have to do it again after ~<1s.

**Comment by FichteFoll** [comment]
Looks like I was too quick on that. Using the arrow keys while the input has focus doesn't allow navigating the list of results at all. The only thing that changed was that I only have to press tab once.
