### ISSUE TITLE
Feature Request Option: Bookmark to Last Folder

### ISSUE THREAD

**Issue by shawnhcorey** [teddy-gustiaux/default-bookmark-folder#29]
Often I want to bookmark a series of pages to the same folder and having the last folder be the default would save some clicking.

**Comment by teddy-gustiaux** [comment]
This is not the first time this feature is requested (see #19), so I am going to have a look into it. 😃

**Comment by teddy-gustiaux** [comment]
This feature is available in the new version `2.5` for all modes. 😃
