### ISSUE TITLE
Unable to Create New Folder in Bookmark Browser

### ISSUE THREAD

**Issue by tree-frog** [teddy-gustiaux/default-bookmark-folder#30]
The following issue is reproducible on Firefox 60.0.2 on macOS 10.13.5:

When creating a new folder via the context menu in the bookmark explorer (i.e. "Show All Bookmarks"), any new folders are silently created in the location specified by the extension, rather than the current folder in the bookmarks explorer.  This is likely not the intended behaviour.

Thanks!

**Comment by teddy-gustiaux** [comment]
This is indeed not the intended behaviour, thank you for reporting it! 👍
I was able to reproduce the bug and I am going to look into fixing it.

**Comment by teddy-gustiaux** [comment]
The problem should be fix in the new release [`2.4.1`](https://github.com/teddy-gustiaux/default-bookmark-folder/releases/tag/v2.4.1). Please let me know if you are still experiencing the problem with the new version. 😃

**Comment by tree-frog** [comment]
Amazing!  All fixed.  Thanks a bunch!
