### ISSUE TITLE
Option to focus on tags field, instead of name

### ISSUE THREAD

**Issue by sojusnik** [teddy-gustiaux/default-bookmark-folder#32]
As the title says, it would be very handy to have an option that will allow us to have the tags field focused, instead the name of a bookmark, when bookmarking a site (ctrl+d).

As far as I can remember, Firefox used to remember the focused field, but your extension always focuses name.

Observing on Firefox 61.0.1 on Ubuntu 18.04.

**Comment by teddy-gustiaux** [comment]
You are correct, Firefox remembers the last used field (_Name_ or _Tag_) when adding or editing a bookmark through the built-in bookmarking system. I'm using Firefox 62, and I have not seen any issue with this behavior with the add-on installed.

As far as I am aware, no [WebExtension API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks) is provided to select the focused field when bookmarking a page. So unfortunately, my only recommendation would be to update to Firefox 62 and see if you are still encountering the issue.

**Comment by jordansaints** [comment]
You can change the default focused field through the `about:config` page. The setting is named `browser.bookmarks.editDialog.firstEditField`, though I'm not sure what the value you want is—I tried "tags" and "tagPicker". Please let us know if you find it. 🙂

The default value for that field (as of FF 62.0.3) is `namePicker`, so Teddy is correct, it is FF picking that default. (I checked this before I installed the addon.)

**Comment by sojusnik** [comment]
Thanks! The correct value for Tags is `tagsField`.

**Comment by teddy-gustiaux** [comment]
Thank you for your help in closing this issue @jordansaints! 😃 👍
