### ISSUE TITLE
Quick bookmark icon

### ISSUE THREAD

**Issue by scmanjarrez** [teddy-gustiaux/default-bookmark-folder#34]
I have enabled this option, however, nothing happens. I have disabled all my addons and userChrome.css but still not appears.
P.S: Let me know how can I help you debugging the problem.
Firefox 62, 64bits
Windows 10

**Comment by scmanjarrez** [comment]
Ok, seems like I forgot to comment out some code in the userChrome.css, now it's working properly.

**Comment by teddy-gustiaux** [comment]
I'm glad to hear you could fix the problem. Thanks for updating the issue!
