### ISSUE TITLE
New usecase: Extension bookmarks

### ISSUE THREAD

**Issue by mkirisame** [teddy-gustiaux/default-bookmark-folder#35]
Useful addon to watch streamers:
https://addons.mozilla.org/en-US/firefox/addon/twitch_5/

Open tabs look like:
moz-extension://5732a25f-310f-4ada-88a5-aa33425dc340/player.html?channel=kimdduddi

Observation:
Bookmarks will goo into the Mozilla forced directory "Other bookmarks" instead of the user defined one through your addon.

I don't know how many usecases you want to cover or not. I just report it as feature request. I assume the amount of bookmarks created this way may be low. It is a nice to have feature, but not a must have.

Thanks again for resolving every issue so far! Very important addon to me that you made.

**Comment by teddy-gustiaux** [comment]
Hello! Thank you for your feedback and sorry for the late response.

If possible, I am more than willing to support this use case in the extension. 😃 Could you confirm that you are still experiencing this issue with the new released version `2.5`? I have tried to replicate the problem but failed to do so. Thanks in advance!

**Comment by mkirisame** [comment]
Being on v2.5.0 now it seems to work out of the box. Over a month ago the issue could be reproduced, now even extension bookmarks are moved nicely. Merci!

**Comment by teddy-gustiaux** [comment]
Wonderful! I am happy to hear it is working now! 😃
