### ISSUE TITLE
This extension does not work after updating to Firefox Dev 84.0b2

### ISSUE THREAD

**Issue by duongdominhchau** [teddy-gustiaux/default-bookmark-folder#356]
# This is a Bug Report

## Description
After the update to 84.0b2, the extension does nothing when bookmarking. The directory shown in the bookmark dialog is the most recently used directory, not the one configured in this extension.

## Expected behavior
The **Folder** drop-down list in **New Bookmark** dialog is set to the directory configured in this extension instead of most recently used directory.

## Specifications

- Version of the add-on: 2.13.0
- Firefox edition: Developer Edition
- Firefox version: 84.0b2
- Firefox language: English
- Platform/OS: ArchLinux

**Comment by bxqgit** [comment]
Yes, doesn't work!

**Comment by teddy-gustiaux** [comment]
Thank you for reporting the issue! I will be looking into it as soon as I can (hopefully this weekend). 🙂

**Comment by duongdominhchau** [comment]
Today I update Firefox Developer Edition to 84.0b7 and the problem disappears. Should I close this issue now or wait for others to confirm it is fixed?

**Comment by WishedGit** [comment]
Not wanting to confuse things too much...but I'm using Firefox Nightly 85.0a1 (2020-12-02) 64-bit in Windows 10 and still have exactly the same problem with this extension (2.13.0) and for about the same period of time.

**Comment by duongdominhchau** [comment]
Confirmed, it breaks again on Firefox Nightly 85.0a1, OS ArchLinux.

**Comment by dmattera** [comment]
I am in a similar, but slightly different boat.

Current version of FF: Developer's Edition, 85.0b4

Issue: Preferences are set so that the "Last used folder" should be used for new single and folder bookmarks but for some reason everything always goes to the Bookmark Toolbar. If I change my preferences to use a specific folder like OP's original issue, it still goes to the Bookmark Toolbar... 

I would expect that if the add on was just simply broken/not working, bookmarks would be reverting to the standard Firefox default of the "Other Bookmarks" folder rather than randomly choosing the Bookmarks Toolbar folder. I do use the Bookmarks Tolbar quite a bit and so perhaps it's just "stuck" on it somehow?

**Comment by dmattera** [comment]
I did some digging around and it looks lke FF 84 introduced some updates that changed Firefox's default bookmark location [from "Other Bookmarks" to the bookmark toolbar](https://bugzilla.mozilla.org/show_bug.cgi?id=1665389) and also added a new pref called `browser.bookmarks.defaultLocation`

I haven't dug into things much further but it seems pretty likely that something they did here is overriding/conflicting with the methods used by this addon to set the default folder. 

Also of note-- Firefox stable version moved to 84 on Dec. 15 and so those users are most likely experiencing the same issue now as well.

**Comment by Hawkzon12** [comment]
> 
> 
> Today I update Firefox Developer Edition to 84.0b7 and the problem disappears. Should I close this issue now or wait for others to confirm it is fixed?

January 13, 2021, it doesn't allow for setting a default folder, it just stays in the last folder I marked to.

**Comment by Hotrodcomp** [comment]
Just noticed the same problem myself - "...it doesn't allow for setting a default folder, it just stays in the last folder I marked to". Also of note, I removed the Default Bookmarks Folder Extension but the Bookmark Star is still there in the Toolbar, and it still works. I am using Firefox version 84.0.2 64 bit.

**Comment by Hawkzon12** [comment]
I still have use of the bookmark app, it's just that suddenly it won't keep the default folder.Hawkzon12

    On Thursday, January 14, 2021, 4:16:39 PM EST, Hotrodcomp <notifications@github.com> wrote:  
 
 


Just noticed the same problem myself - "...it doesn't allow for setting a default folder, it just stays in the last folder I marked to". Also of note, I removed the Default Bookmarks Folder Extension but the Bookmark Star is still there in the Toolbar, and it still works. I am using Firefox version 84.0.2 64 bit.

**Comment by alexis-jon** [comment]
I have the same problem of the last folder being used rather than the default folder selected in the add-on, when I save new bookmarks via the Firefox star icon.
Firefox 84.0.2 (64-bit)

**Comment by teddy-gustiaux** [comment]
Hello all- and thank you for reporting on these problems. I have finally had some time to dive deeper into this. As a result, I have opened the meta issue #399 you see linked above. I encourage you to have a read if you want more details (it is a long piece but there is a TL;DR at the top). 🙂
