### ISSUE TITLE
Reverted to version 2.4.1

### ISSUE THREAD

**Issue by Merseybuoy** [teddy-gustiaux/default-bookmark-folder#38]
I used version 2.5 for just 5 minutes. Please reinstate the 'Only show page as bookmarked if the bookmark is in the folder selected above' option.

**Comment by teddy-gustiaux** [comment]
I will be adding back this feature very soon in the next release. Sorry for the inconvenience.

**Comment by Merseybuoy** [comment]
> 
> 
> I will be adding back this feature very soon in the next release. Sorry for the inconvenience.

Thank You. Much appreciated.

**Comment by teddy-gustiaux** [comment]
This feature has been added back as part of the [new version `2.6`](https://github.com/teddy-gustiaux/default-bookmark-folder/releases/tag/v2.6.0). 🙂
