### ISSUE TITLE
How can I use it in Chrome？

### ISSUE THREAD

**Issue by hahahahahacn** [teddy-gustiaux/default-bookmark-folder#380]
# This is a Question

**Description**
I've been experimenting with Edge recently, wondering how to use the plugin
How can I use it in Chrome or Edge

**Comment by teddy-gustiaux** [comment]
This add-on is only supporting Firefox at the moment.

In theory, as all modern browsers (Firefox, Chrome, Edge, etc.) support the WebExtension system / APIs the add-on is built upon, one could technically port it over for other browsers. This would also necessitate to adapt to the specificities of each browser. It is not in my short-term plans to do this- but that could change in the future.
