### ISSUE TITLE
Possible to avoid connections to `fontawesome.com` on the options page?

### ISSUE THREAD

**Issue by FatOrangutan** [teddy-gustiaux/default-bookmark-folder#39]
I try to minimize connections to third parties on the websites I visit so I find it a bit unfortunate that the options page of this extension makes remote connections to `fontawesome.com`.

Additionally the origin request header includes the uuid of the extension (randomly generated for every installation) which can be used to uniquely identify the user:

![d02cf970-acd4-4063-a5b8-eab5969f09b7](https://user-images.githubusercontent.com/8336638/47286465-74a93d00-d60c-11e8-8570-efe881e13c26.png)

Would it be possible to avoid these connections? Perhaps package static copies of the stylesheets and the font?

Thanks.

**Comment by teddy-gustiaux** [comment]
That is definitely possible! 🙂

**Comment by teddy-gustiaux** [comment]
This has been fixed as part of the [new version `2.6`](https://github.com/teddy-gustiaux/default-bookmark-folder/releases/tag/v2.6.0). 🙂
