### ISSUE TITLE
[Nitpicks] Assign a favicon to the options page and use title case on the context menu labels

### ISSUE THREAD

**Issue by FatOrangutan** [teddy-gustiaux/default-bookmark-folder#40]
Adding a favicon to the options page will make it easier to identify it in a bunch of tabs.

Secondly, and this is super nitpicky, but Firefox design guidelines [suggest](https://design.firefox.com/photon/copy/capitalization.html#title-case-on-desktop) using the title case on context menu labels. This will match how Firefox's own context menu entries look.

**Comment by teddy-gustiaux** [comment]
I think adding a favicon is a good idea! 🙂

Regarding your second point, I am not opposed to it and I have open a more generic dedicated issue (#41).

**Comment by teddy-gustiaux** [comment]
This has been added as part of the [new version `2.6`](https://github.com/teddy-gustiaux/default-bookmark-folder/releases/tag/v2.6.0). 🙂
