### ISSUE TITLE
New 'browser.bookmarks.defaultLocation' Overrides and Interferes with Default Bookmark Folder

### ISSUE THREAD

**Issue by WCityMike** [teddy-gustiaux/default-bookmark-folder#400]
I have Default Bookmark Folder installed.  Nonetheless, it's stopped working altogether.  It's also not acting in Firefox's default manner, either -- whenever I go to bookmark all tabs, it wants to save it to the Bookmarks Toolbar.  I'd appreciate any insight that could be offered.

**Comment by WCityMike** [comment]
Some quick follow-up from a discovered e-mail, from [Wes Kochar on Nov. 8](https://www.mail-archive.com/enterprise@mozilla.org/msg04118.html):

> [This extension](https://addons.mozilla.org/en-US/firefox/addon/default-bookmark-folder/) lets you define a default location for new bookmarks.
> 
> Beyond that, there's [bug 1432604](https://bugzilla.mozilla.org/show_bug.cgi?id=1432604), which just landed in Nightly builds a few days ago for what will become Firefox 84 in a month or two. It makes Firefox remember the most recently selected bookmark destination, so users would only need to pick a different destination folder once, and it would continue to be used from then on.
> 
> I think that patch adds a preference to track the most-recently-selected folder. From some quick testing, it looks like `browser.bookmarks.defaultLocation` gets set to a value of "menu________" or "toolbar_____" for the bookmarks menu or bookmarks toolbar, respectively. I'm unsure what the underscores represent (or if they're even necessary), but in theory, you might be able to use a policy to pre-set that preference to one of those values, and it might get a saner default for your users.

So I am assuming that the new value is interfering with Default Bookmark Folder altogether.

**Comment by teddy-gustiaux** [comment]
Hi @WCityMike and thank you for reporting this issue! You are indeed correct, and it is linked to the Firefox "2020H2 bookmarks improvements" project. I have created the meta issue #399 regarding this, so I would encourage you to have a read if you want more details (it is a long piece but there is a TL;DR at the top). 🙂
