### ISSUE TITLE
Bookmarks adding in strange place

### ISSUE THREAD

**Issue by Dantasstic** [teddy-gustiaux/default-bookmark-folder#405]
# This is a Bug Report

## Description
Bookmarks are added the 7th position on Bookmark Menu, instead of at the bottom

## Steps to reproduce the problem

1. add a bookmark
2. open bookmark menu
3. instead of being in the expected spot, the bookmark is seven down from the top of my bookmarks

## Expected behavior
The bookmarks always used to go to the bottom of the list, where I wanted them to go

## Specifications

- Version of the add-on: 3.0.0

- Firefox edition: Firefox (regular edition)
- Firefox version: 85
- Firefox language: English

- Platform/OS: Windows
- Platform/OS version: 2004

**Comment by AMGPilot** [comment]
I have the same issue except that the bookmark is placed at the top instead of the bottom as I have chosen in the options.

**Comment by teddy-gustiaux** [comment]
Thank you for reporting this issue! I was able to reproduce it. I will be working on releasing a fix. 🙂

**Comment by teddy-gustiaux** [comment]
Version 3.1.0 containing the fix for this version has been submitted to AMO for review.

**Comment by teddy-gustiaux** [comment]
Version 3.1.0 has been approved and is being distributed.
