### ISSUE TITLE
Not respecting setting to add bookmark to top versus bottom of folder

### ISSUE THREAD

**Issue by Snackhole** [teddy-gustiaux/default-bookmark-folder#407]
# This is a Bug Report

## Description
The setting to add new bookmarks to the top of the default bookmark folder appears to be treated as enabled regardless of the toggle switch status.

## Steps to reproduce the problem

1. Select a default bookmark folder.
2. Disable adding new bookmarks to the top of the folder.
3. Add a new bookmark.
4. Observe that the bookmark is at the top of the folder, not the bottom.

## Expected behavior
Adding the bookmark to the top of a folder should only happen if that setting is enabled.

## Specifications

- Version of the add-on: 3.0.0
- Firefox edition: Firefox (regular edition)
- Firefox version: 84.0.2
- Firefox language: English
- Platform/OS: Linux
- Platform/OS version: Kubuntu 20.04

## Additional context
This is a very recent change, though I'm not sure what the last properly working version was.

**Comment by teddy-gustiaux** [comment]
Thank you for reporting this issue! I very recently released version 3.1.0 that does contain a fix around this setting. Would it be possible for you to confirm the issue is still happening with this version? Thanks! 🙂

**Comment by Snackhole** [comment]
New version 3.1.0 seems to fix it!
