### ISSUE TITLE
Sort bookmarks folders to most recently used.

### ISSUE THREAD

**Issue by lascetic** [teddy-gustiaux/default-bookmark-folder#482]
When bookmarking using the bookmark dialog, can the folders be listed according to most recently used?

I am not sure if this is firefox or the addon's issue, but it used to do so by default and now it doesn't seem to do it anymore. When pressing ctrl+D to bring up the bookmark dialog, one sees the default folder. Clicking on the drop down arrow right next to the default folder, it gives you the option to choose which folder you want to store your bookmark and below that the six most recently (or most often) used folders. However, in my case this list of six folders doesn't seem to update anymore accordingly. Any way to fix it?

**Comment by teddy-gustiaux** [comment]
Sorry for the late reply on this. The interface/dialog that shows up when using the `Ctrl+D` shortcut or the browser's default bookmarking icon (i.e. Firefox's native bookmarking dialog) cannot be controlled by an add-on.

As far as I know, the behavior you are describing would be driven only by Firefox directly. Therefore, I will close this issue as there is nothing I can do to address the reported behavior. I hope this answers your question.
