### ISSUE TITLE
Firefox questions

### ISSUE THREAD

**Issue by jjohart** [teddy-gustiaux/default-bookmark-folder#50]
I'm unable to do what Firefox used to, that is, bookmark a page, and the dumb drop down box would let me click which folder I want it to go to.  Did Firefox change this..it seems to be an issue on more than one of my macs.  This app-default bookmark-only lets you redirect to ONE folder, which is kind of narrow minded, since most google users of Firefox are complaining how to get the book marks choice drop down to show its head again.  
I haven't found an answer as to how to return this feature to Firevox, but it may not be possible?

**Comment by JJJoseph** [comment]
I miss this FF bookmark tool, mostly because it's so difficult to find previous bookmarks. If I bookmark to the wrong location, I can't find it later.  Bookmarks should be drop-dead simple, but they've become so complicated.

**Comment by teddy-gustiaux** [comment]
@jjohart From what you are saying, it looks like you have set up the bookmark editor to not be displayed when creating bookmarks with the native Firefox star icon in the address bar. You can find more details on the [official help page](https://support.mozilla.org/en-US/kb/bookmarks-firefox#w_how-do-i-change-the-name-or-location-of-a-bookmark), but in a nutshell:
- Bookmark a page by clicking the Firefox star icon
- Click it again to have the bookmark editor appear and make sure to enable *Show editor when saving*
- Next time you try to bookmark a page, the bookmark editor will appear. You can then select the folder you want by using the drop-down menu. You can also click on the arrow on the right to display a list of all bookmarks folders. 

![image](https://user-images.githubusercontent.com/26365722/57962536-d3564100-78e5-11e9-9d10-97ba5c49b403.png)

@JJJoseph Please see my response above. If you have completely lost a bookmark, you can also try to search by going to the Awesome bar, and entering an asterisk (`*`) followed by your search terms. Only the bookmarks will show up. You might be able to find the one you are looking for through this method.

I hope this helps you both. 🙂 As these questions are related to Firefox itself and not to Default Bookmark Folder, I would recommend asking this type generic Firefox support questions to their dedicated forums, where people will be able to help. If you have a question, bug report or feature request about this add-on, please feel welcome to open another issue in this repository.
