### ISSUE TITLE
Optimize Interface

### ISSUE THREAD

**Issue by Machou** [teddy-gustiaux/default-bookmark-folder#54]
Hi :)

- Maybe you could improve your interface, there is a missing icon on the "Quick Marking" tab: https://i.imgur.com/9dhmZap.jpg

- On the first tag < section >, a 3rem padding is really huge, I think 1, even 0 is more appropriate.

- The font-size of Bulma's 16px body is a little too much too, I think a 14px would be enough and it improves visual comfort.

- The tabs don't have a suitable order, I think the "Release Notes" tab should be in the last but one.
This order is more logical: Marking integrated in Firefox - Quick marking - Release notes - About
Maybe, combine About and Release Notes.

With these settings, I find that the rendering is much better.

- New interface : https://i.imgur.com/f8gBtUS.png
- Firefox 66.0.2 - Win 7

----

- Pourrai-tu peut-être améliorer ton interface, il y a une icône manquante sur l'onglet "Marquage rapide" : https://i.imgur.com/9dhmZap.jpg

- Sur la première balise < section >, un padding de 3rem est vraiment énorme, je pense que 1, voir 0 est plus approprié.

- Le font-size du body de 16px de Bulma, est un peu trop aussi, je pense qu'un 14px suffirait largement et ça améliore le confort visuel.

- Les onglets n'ont pas un ordre adaptés, je pense que l'onglet "Notes de version" devrait être en avant dernier.
Cet ordre est plus logique : Marquage intégré à Firefox - Marquage rapide - Notes de version - A propos
Voir, combiner A propos et Notes de version.

Avec ces réglages, je trouve que le rendu est bien meilleur.

- Le rendu : https://i.imgur.com/f8gBtUS.png
- Firefox 66.0.2 - Win 7

**Comment by Machou** [comment]
Je vois que tu as fait pas mal de modif, vraiment très sympa cette version !

On peut cloturer l'issue :P

bonne chance

**Comment by teddy-gustiaux** [comment]
Thanks! 🙂 I do think your idea of combining the *release notes* section to the *about* one would be nice, especially now that the release notes are hosted on GitHub. I would like to make the changes in a future version!
