### ISSUE TITLE
Issues on Firefox 113 when selecting a directory during manual save with CTRL+D

### ISSUE THREAD

**Issue by spacesynth** [teddy-gustiaux/default-bookmark-folder#543]
# This is a Bug Report

## Description
Manually selecting a directory fails storing the bookmark in the desired location.

## Steps to reproduce the problem

1. CTRL+D
2. select another directory like "food links"
3. the bookmark is saved to the main directory not the "food links" directory
4. retrying with CTRL+D shows the "food links" directory (in the popout), but it will always be in the main directory (actual location)

## Expected behavior
Save to the selected directory if I override the default one in the CTRL+D popout menu. This is clearly an issue caused by Mozilla updating Firefox, as the addon worked perfectly before.

## Specifications

- Version of the add-on: latest from 2021 (is the project dead?)
- Firefox edition: Firefox 113 (stable)
- Firefox version: DevEd 114
- Firefox version: Nightly 115
- Firefox language: English
- Platform/OS: Windows
- Platform/OS version: 19045.2965 windows 10 22h2 pro

## Screenshots
Should be easy enough to reproduce, but if really required I can record the issue.

## Additional context
If you need logs I can provide them.

**Comment by siffegh** [comment]
I can reproduce the problem on v113.0/Win7.

**Comment by vitalii2011** [comment]
I confirm. There was such an inconvenience in Firefox 113.

**Comment by Dainslaif** [comment]
This is still happening, but has changed slightly.  It will still force-save to the default directory initially, but now when you Ctrl-D to review the bookmark, it shows the bookmark's actual location.  Updating to the desired directory does move the bookmark.

**Comment by spacesynth** [comment]
```user_pref("browser.bookmarks.defaultLocation", "menu________");```

I'm abandoning this issue and will enforce the default bookmark folder via user.js permanently which enforces prefs.js on launch.
