### ISSUE TITLE
Has the project been abandoned?

### ISSUE THREAD

**Issue by lascetic** [teddy-gustiaux/default-bookmark-folder#546]
I was just wondering if the project has been abandoned, so I can uninstall it as it is not working any more as expected. Has been a very useful tool and I appreciate the effort, but an update either of the addon or on the status of the project is overdue. Many thanks.

**Comment by siffegh** [comment]
> I was just wondering if the project has been abandoned, so I can uninstall it as it is not working any more as expected. Has been a very useful tool and I appreciate the effort, but an update either of the addon or on the status of the project is overdue. Many thanks.

It appears so, but after hunting around for a while I discovered a new one's been made. Wonder why @teddy-gustiaux hasn't publicized it?

https://addons.mozilla.org/en-US/firefox/addon/quick-bookmarking

https://github.com/teddy-gustiaux/quick-bookmarking

**Comment by lascetic** [comment]
> > 
> 
> It appears so, but after hunting around for a while I discovered a new one's been made. Wonder why @teddy-gustiaux hasn't publicized it?
> 
> https://addons.mozilla.org/en-US/firefox/addon/quick-bookmarking
> 
> https://github.com/teddy-gustiaux/quick-bookmarking

Thanks a lot for this. Have you tried it?

**Comment by siffegh** [comment]
Yes. It seems to work OK exc. the kb shortcut. But I didn't test all features.

**Comment by lascetic** [comment]
> Yes. It seems to work OK exc. the kb shortcut. But I didn't test all features.

That's great news. I have started losing hope on the other as it's been broken for months. Like you said, strange it's not promoted. 
I really appreciate your help.

**Comment by nuenuewei** [comment]
quick bookmarking is a subfeature of this extension. It seems this other extension is just a standalone version of that that doesn't do what this one does.
