### ISSUE TITLE
Dons !

### ISSUE THREAD

**Issue by Machou** [teddy-gustiaux/default-bookmark-folder#62]
Hello,

I would like to make a donation, can you add a page or section for the donation?

Bitcoin, PayPal, Patreon, etc.

Thank you for all the work you do;)

====

Bonjour,

Je souhaiterai effectuer un don, peux-tu ajouter une page ou une section pour la donation ?

Bitcoin, PayPal, Patreon, etc.

Merci pour tout le travail que tu fais ;)

**Comment by teddy-gustiaux** [comment]
Thanks a lot, I appreciate it! 🙂 I will look into setting something up- I am not sure yet which one(s)- and add links to it.
