### ISSUE TITLE
Add-on stopped working in Firefox 67.0.2 (64-bit)

### ISSUE THREAD

**Issue by iG8R** [teddy-gustiaux/default-bookmark-folder#68]
# This is a Bug Report

## Description
What ever folder I select Firefox still propose to save bookmarks in "Other Bookmarks".

## Steps to reproduce the problem

1. Install/Update Firefox to 67.0.2
2. Install Default Bookmark Folder Add-on
3. Set "Select where new bookmarks will be added:" option to any Folder except "Other Bookmarks"
4. Try to save any bookmark

## Expected behavior
Any time I try to add bookmark I'd like to see folder that is selected in add-on but not default "Other Bookmarks".

## Specifications

- Version of the add-on: 2.10

- Firefox edition: Firefox (regular edition)
- Firefox version: 67.0.2 (64-bit)
- Firefox language: English

- Platform/OS: Windows 10 1803build

**Comment by thosf** [comment]
I also noticed that while the computer is on, and I close Firefox, when starting Firefox again, the default bookmark folder that I selected was lost. Hope this helps.

BTW: I now have Firefox Quantum 67.0.4 (64-bit) which produces this issue.

**Comment by teddy-gustiaux** [comment]
Thank you for reporting this issue @iG8R and for providing the details. 👍 
I have been trying to reproduce the problem with an almost exact setup, and I was unfortunately unsuccessful.

I do have a few questions that could help me:
- If you try to set other options, such as toggles (like _Add new bookmarks to the top of the selected folder_) or folder selection for the quick bookmark icon, are they retained or not?
- If you set an option and refresh the page, is the selection retained?

On a different approach, I do not know if you are familiar with Firefox profiles? They are where [Firefox stores your bookmarks, passwords and other user data](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data).

If you can create a new profile, and test the add-on to see if the problem still exists, that would be very helpful and would rule out a number of possible issues (see #66) or a corrupted profile (which can sometimes happen). This [link explains how to use the Profile Manager to create and remove Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles). Please let me know if you need any help in this regard.

Thanks for your help! 🙂

**Comment by iG8R** [comment]
First of all I'd want to thank you @teddy-gustiaux for the excellent addon.
Recently I updated Firefox to 67.0.4 (64-bit) version and Default Bookmark Folder started working correctly again.
Regarding you question earlier when I had 67.0.2 version:
1. Yes, all toggles and folder selection are retained but addon still didn't work correctly.
2. Yes, all options have been retained after refreshing page but, again, addon didn't work correctly.
3. The same was with the new profile also - the issue didn't disappear.

Thank you.

**Comment by teddy-gustiaux** [comment]
Thanks a lot! I am glad to hear things are back to normal with 67.0.4- although at this point I am not sure what made the add-on fail with the previous minor version. I am going to close this issue, but feel free to open a new one if you are experiencing any other problems. 🙂
