### ISSUE TITLE
Extension is currently not working with CTRL + D Shortcut

### ISSUE THREAD

**Issue by grandslammer** [teddy-gustiaux/default-bookmark-folder#7]
Hey I've noticed a recent issue with the extension where it is not putting my new bookmarks into the set location when I use CTRL + D. It is however working as expected when I use the Firefox bookmark icon in the address bar (not the extension's quick bookmark icon - I have that option disabled.) The bookmarks are going into the "Bookmarks Menu" when I use the keyboard shortcut, but they are going into the correct folder when I click the blue icon.

This is a recent issue which I've only noticed within the last 24 - 48 hours.

**Comment by teddy-gustiaux** [comment]
Hello! Thanks for reporting this issue. It seems to have been introduced with the latest version of the add-on. I have been able to reproduce the bug and I am going to work on a fix!

**Comment by teddy-gustiaux** [comment]
It appears the default bookmark folder is different for the bookmarking shortcut (Ctrl+D) , as well as for the context menu bookmarking on the stable version of Firefox only (57.x). Commit 83dcaa0 fixes this problem. 😃 

I have also published version `2.1.1` on AMO , which includes the bugfix. Please do not hesitate to let me know if you are still experiencing the issue after the update!
