### ISSUE TITLE
Problem with right mouse button

### ISSUE THREAD

**Issue by storm483** [teddy-gustiaux/default-bookmark-folder#9]
The plugin work fine for weeks but now don't set the correct folder with right button. It's all ok with the other built-in boookmarking system of firefox. I've just tried to reinstall the plugin without results.
Firefox 57.0.2 (64bit) win10

**Comment by teddy-gustiaux** [comment]
Thank you for the bug report! It appears this bug was linked to the same problem as issue #7.

I have published version `2.1.1` on AMO , which includes the bugfix. Please do not hesitate to let me know if you are still experiencing the issue after the update! 😃

**Comment by storm483** [comment]
Now It'all OK! Thank U so much!!!
