### ISSUE TITLE
Quick bookmark

### ISSUE THREAD

**Issue by Dman44** [teddy-gustiaux/default-bookmark-folder#92]
# This is a Bug Report

## Description
A clear and concise description of what the bug is. when you gotto quick bookmark and begin tyoing the name of the desired bookmark you get 1 or more options but when you click the one you want half the time it doesn't store the bookmark in the selected folder instead it puts it in "Other Folders" folder 

## Steps to reproduce the problem

1. 
2. 
3. 
4. 

## Specifications

- Version of the add-on:

- Firefox edition: Firefox (regular edition) / Developer Edition / Beta / Nightly / Other (please specify)
- Firefox version:
- Firefox language: English / Other (please specify)

- Platform/OS: Windows / macOS / Linux / Other (please specify)
- Platform/OS version:

**Comment by teddy-gustiaux** [comment]
Thanks for reporting this problem @Dman44!
It turns out others have experienced the same issue, so I am closing this particular issue to avoid duplicates. Please refer to issue #111 for details, but know that a fix is ready and will be out with the next version, which I hope to be soon! 🙂
